settings:
  timer: 5
  games-per-mode: 1
  ghead-cooldown: 2
  elo:
    default: 1000
    kill: 10
    death: 10
    win: 20
  border:
    0:
      timer: 0
      size: 100
    1:
      timer: 100
      size: 50
    2:
      timer: 200
      size: 20
  leaderboards:
    entries: 15
    world: world
    classic:
      x: 7
      y: 68
      z: 1
    nodebuff:
      x: 17
      y: 68
      z: 1