settings:
  timer: 5
  games-per-mode: 8
  elo:
    default: 1000
    kill: 10
    death: 10
    win: 20
  border:
    0:
      timer: 0
      size: 100
    1:
      timer: 100
      size: 50
    2:
      timer: 200
      size: 20