name: RankedUHCDeathmatch
author: [ MINTY ]
website: https://mintydev.xyz
main: xyz.mintydev.uhcdeathmatch.UHCDeathMatch
version: 1.0.0
depend: [HolographicDisplays]
commands:
  leave:
    description: leave a uhc ranked uhcdeathmatch game
    aliases: l, hub, lobby
  duel:
    description: duel a player
  elo:
    description: get the elo of a player
  gamestop:
    description: game stop